import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';
export default function AdminClient(){const [items,setItems]=useState([]),[comments,setComments]=useState([]),[tab,setTab]=useState('projects'),[form,setForm]=useState({title:'',description:'',image:'',video:'',type:'projects'}),[msg,setMsg]=useState(''),[upload,setUpload]=useState(null);const router=useRouter();
async function load(){const r=await fetch('/api/admin/content');if(r.status===401)return router.push('/login');const d=await r.json();setItems(d.items||[]);const cr=await fetch('/api/admin/comments');if(cr.ok)setComments((await cr.json()).items||[])}
useEffect(()=>{load()},[]);
async function save(e){e.preventDefault();const r=await fetch('/api/admin/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,type:tab})});const d=await r.json();setMsg(r.ok?'تم الحفظ بنجاح':(d.error||'حدث خطأ'));if(r.ok){setForm({title:'',description:'',image:'',video:'',type:tab});load()}}
async function del(id){if(!confirm('حذف هذا المحتوى؟'))return;await fetch('/api/admin/content?id='+id,{method:'DELETE'});load()}
async function moderate(id,status){await fetch('/api/admin/comments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});load()}
async function delComment(id){if(!confirm('حذف التعليق؟'))return;await fetch('/api/admin/comments?id='+id,{method:'DELETE'});load()}
async function uploadFile(e){e.preventDefault();if(!upload)return;const fd=new FormData();fd.append('file',upload);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const d=await r.json();setMsg(r.ok?'تم رفع الملف: '+d.url:(d.error||'فشل الرفع'));if(r.ok)setForm(f=>({...f,image:d.type==='image'?d.url:f.image,video:d.type==='video'?d.url:f.video}))}
async function logout(){await fetch('/api/logout',{method:'POST'});router.push('/')}
const title=tab==='projects'?'المباني':tab==='finishing'?'التشطيبات':tab==='investments'?'الاستثمارات':'التعليقات';
return <main className="admin-page"><header className="adminbar"><strong>عقارات الهضبة — لوحة التحكم</strong><button onClick={logout} className="btn ghost darkbtn">تسجيل الخروج</button></header><div className="admin-layout"><aside><button onClick={()=>setTab('projects')}>المباني</button><button onClick={()=>setTab('finishing')}>التشطيبات</button><button onClick={()=>setTab('investments')}>استثمار</button><button onClick={()=>setTab('comments')}>التعليقات</button></aside><section className="admin-main"><div className="section-head"><div><div className="eyebrow dark">إدارة المحتوى</div><h1>{title}</h1></div></div>
{tab!=='comments'?<><form className="form admin-form" onSubmit={save}><input required placeholder="العنوان" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea required rows="4" placeholder="الوصف" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="رابط الصورة" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><input placeholder="رابط الفيديو (اختياري)" value={form.video} onChange={e=>setForm({...form,video:e.target.value})}/><button className="btn primary">نشر المحتوى</button></form><form className="form admin-form" onSubmit={uploadFile}><h3>رفع صورة أو فيديو</h3><input type="file" accept="image/*,video/*" onChange={e=>setUpload(e.target.files?.[0]||null)}/><button className="btn ghost darkbtn">رفع الملف</button></form><div className="admin-list">{items.filter(x=>x.type===tab).map(x=><div className="admin-item" key={x._id}><div><strong>{x.title}</strong><p>{x.description}</p></div><button className="btn danger" onClick={()=>del(x._id)}>حذف</button></div>)}</div></>:<div className="admin-list">{comments.map(c=><div className="admin-item" key={c._id}><div><strong>{c.name}</strong><p>{c.comment}</p><small>الحالة: {c.status}</small></div><div className="actions"><button className="btn primary" onClick={()=>moderate(c._id,'approved')}>موافقة</button><button className="btn ghost darkbtn" onClick={()=>moderate(c._id,'hidden')}>إخفاء</button><button className="btn danger" onClick={()=>delComment(c._id)}>حذف</button></div></div>)}{!comments.length&&<div className="empty">لا توجد تعليقات.</div>}</div>}{msg&&<small className="notice">{msg}</small>}</section></div></main>}